---
name: GitHub Actions OpenStack CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run:  pip install python-openstackclient python-heatclient
      - name: List files
        run: ls -al
      - name: Ansible version
        run: ansible --version
      - name: OpenStack version
        run: openstack --version
      - name: OpenStack help
        run: openstack --help
